application:
  appName: "cmdb"
  description: "微服务资产管理平台"
  domain: "example.com"

log:
  otlp: true

http:
  enabled: true
  host: "0.0.0.0"
  port: 8083
  otlp: true

grpc:
  enabled: true
  host: "0.0.0.0"
  port: 18083
  otlp: true

otlp:
  httpEndpoint: "10.54.44.78:4318"
  grpcEndpoint: "10.54.44.78:4317"
  enableTLS: false

mauditClient:
  host: "127.0.0.1"
  port: 18081
  token: "maudit-token"

mcenterClient:
  host: "127.0.0.1"
  port: 18082
  token: "mcenter-token"

datasource:
  otlp: true
  host: "127.0.0.1"
  port: 3306
  database: "CloudManager"
  username: "root"
  password: "redhat"
  debug: true